account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('complete-provisional-registration/', views.CompleteProvisionalRegistration.as_view(), name='complete_provisional_registration'),
    path('activated/<token>/', views.Activated.as_view(), name='activated'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password-reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('send-password-reset/', views.AcceptPasswordReset.as_view(), name='accept_password_reset'),
    path('set-password/<uidb64>/<token>/', views.SetPassword.as_view(), name='set_password'),
    path('complete-password-reset/', views.CompletePasswordReset.as_view(), name='complete_password_reset'),
    # NOTE: internal url of dashboard
    path('user-detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('update-user/<int:pk>/', views.UpdateUser.as_view(), name='update_user'),
    path('password-change/<int:pk>', views.PasswordChange.as_view(), name='password_change'),
]

budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('create/', views.Create.as_view(), name='create'),
    path('expenditure-plan-save/', views.expenditure_plan_save, name='expenditure_plan_save'),
    path('edit/', views.Edit.as_view(), name='edit'),
    path('expenditure-plan-update/', views.expenditure_plan_update, name='expenditure_plan_update'),
    path('copy-last-month-expenditure-plans/',
         views.copy_last_month_expenditure_plans,
         name='copy_last_month_expenditure_plans'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('terms_of_service/', views.TermsOfService.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),
]

lp/urls.py
from django.urls import path

from . import views

app_name = 'lp'

urlpatterns = [
    path('general/', views.General.as_view(), name='general'),
]

sumuma/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
import environ
from rest_framework import permissions
from rest_framework import routers

from kakeibo.views.api.kakeibo import CategoriesViewSet, IncomesViewSet, ExpendituresViewSet
from sumuma.settings import ADMIN_DASHBOARD_PATH

env = environ.Env()

schema_view = get_schema_view(
    openapi.Info(
        title="SUMUMA API",
        default_version='v1',
        description="SUMUMA Swagger UI",
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticatedOrReadOnly],
)

router = routers.DefaultRouter()
router.register(r'categories', CategoriesViewSet, basename='categories')
router.register(r'incomes', IncomesViewSet, basename='incomes')
router.register(r'expenditures', ExpendituresViewSet, basename='expenditures')

urlpatterns = [
    path(ADMIN_DASHBOARD_PATH, admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('kakeibo/', include('kakeibo.urls')),
    path('analyses/', include('analyses.urls')),
    path('contact/', include('contact.urls')),
    path('budget/', include('budget.urls')),
    path('shopping/', include('shopping.urls')),
    path('lp/', include('lp.urls')),
    # NOTE: api routers
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # NOTE: swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('openapi/', get_schema_view(
    #     title="Your Project",
    #     description="API for all things …",
    #     version="1.0.0"
    # ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url': 'openapi-schema'}
    # ), name='swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

sumuma/templates/503.html
<!doctype html>
<html lang="ja">
<head>
  {% include 'gtm.html' %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- favicon -->
  <link rel="icon" type="image/png" href="/static/home/images/favicon.png" alt="">

  <title>SUMUMA</title>
</head>
<body>
<div style="text-align: center;">
  <h1>メンテナンス中</h1>
  <p>時間をあけてから、再度アクセスしてください。</p>
  <p><a href="https://twitter.com/sumumacom" target="_blank" rel="noopener">SUMUMA公式ツイッターでサービス情報を見ることができます。</a></p>
</div>
</body>
</html>

sumuma/templates/auth_base.html
<!doctype html>
<html lang="ja">
  {% load tailwind_tags %}
  <head>
    {% include 'gtm.html' %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'home/images/favicon.png' %}" alt="">
    <link rel="apple-touch-icon" href="{% static 'home/images/favicon.png' %}" alt="">
    <!-- account style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/style.css' %}">
    <title>SUMUMA</title>
    {% tailwind_css %}
  </head>
  <body class="bg-green-50">
    {% include 'gtm_noscript.html' %}
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <div class="w-full fixed shadow py-4 px-3 bg-white">
      <a class="text-xl font-bold text-gray-900 hover:text-gray-900" href="{% url 'home:top' %}">SUMUMA</a>
    </div>
    <div class="h-screen flex justify-center items-center">
      {% block content %}
      {% endblock %}
    </div>
    <script type="text/javascript" src="{% static 'account/js/signup.js' %}"></script>
  </body>
</html>

sumuma/templates/auth_user_secondary_base.html
<!doctype html>
<html lang="ja">
  {% load tailwind_tags %}
  <head>
    {% include 'gtm.html' %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'home/images/favicon.png' %}" alt="">
    <link rel="apple-touch-icon" href="{% static 'home/images/favicon.png' %}" alt="">
    <!-- account style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/style.css' %}">
    <title>SUMUMA</title>
    {% tailwind_css %}
  </head>
  <body class="bg-green-50">
    {% include 'gtm_noscript.html' %}
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <div class="w-full fixed shadow py-4 px-3 bg-white">
      <a class="text-xl font-bold text-gray-900 hover:text-gray-900" href="{% url 'home:top' %}">SUMUMA</a>
    </div>
    <div class="mx-auto h-screen pt-20">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

sumuma/templates/gtm.html
<!-- Google Tag Manager -->
<script>(function (w, d, s, l, i) {
  w[l] = w[l] || [];
  w[l].push({
    'gtm.start':
      new Date().getTime(), event: 'gtm.js'
  });
  var f = d.getElementsByTagName(s)[0],
    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
  j.async = true;
  j.src =
    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
  f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-TKVLP3X');</script>
<!-- End Google Tag Manager -->

sumuma/templates/gtm_noscript.html
<!-- Google Tag Manager (noscript) -->
<noscript>
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TKVLP3X"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->

sumuma/templates/home_base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
  {% include 'gtm.html' %}
  <!-- Ordinary meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="ただの家計簿で終わらせない、家計簿をもっと賢く美しく">
  <meta name="keywords" content="家計簿">
  <meta property="og:title" content="SUMUMA"/>
  <meta property="og:site_name" content="SUMUMA"/>
  <meta property="og:description" content="ただの家計簿で終わらせない、家計簿をもっと賢く美しく"/>
  <meta property="og:url" content="https://sumuma.com"/>
  <meta property="og:type" content="website">
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'home/images/daifuku.png' %}"/>
  <meta property="og:locale" content="ja_JP"/>
  <meta name="theme-color" content="#3056d3">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#3056d3">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#3056d3">
  <!-- Google / Search Engine Tags -->
  <meta itemprop="name" content="SUMUMA">
  <meta itemprop="description" content="ただの家計簿で終わらせない、家計簿をもっと賢く美しく">
  <meta itemprop="image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'home/images/daifuku.png' %}">
  <!-- Facebook Meta Tags -->
  <meta property="og:url" content="https://sumuma.com">
  <meta property="og:type" content="website">
  <meta property="og:title" content="SUMUMA">
  <meta property="og:description" content="ただの家計簿で終わらせない、家計簿をもっと賢く美しく">
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'home/images/daifuku.png' %}">
  <!-- Twitter Meta Tags -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="SUMUMA">
  <meta name="twitter:description" content="ただの家計簿で終わらせない、家計簿をもっと賢く美しく">
  <meta name="twitter:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'home/images/daifuku.png' %}">
  <!-- iOS Meta Tags -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="SUMUMA">
  <!-- favicon -->
  <link rel="icon" type="image/png" href="{% static 'home/images/favicon.png' %}" alt="">
  <link rel="apple-touch-icon" href="{% static 'home/images/favicon.png' %}" alt="">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'home/css/animate.css' %}"/>
  <link rel="stylesheet" href="{% static 'home/css/lineicons.css' %}"/>
  <link rel="stylesheet" href="{% static 'home/css/ud-styles.css' %}"/>
  <title>SUMUMA</title>
</head>
<body>
{% include 'gtm_noscript.html' %}
{% block content %}]
{% endblock %}
</body>
</html>

sumuma/templates/home_footer.html
{% load static %}
<footer class="ud-footer wow fadeInUp" data-wow-delay=".15s">
  <div class="shape shape-1">
    <img src="{% static 'home/images/footer/shape-1.svg' %}" alt="shape" />
  </div>
  <div class="shape shape-2">
    <img src="{% static 'home/images/footer/shape-2.svg' %}" alt="shape" />
  </div>
  <div class="shape shape-3">
    <img src="{% static 'home/images/footer/shape-3.svg' %}" alt="shape" />
  </div>
  <div class="ud-footer-widgets">
    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-6">
          <div class="ud-widget">
            <ul class="ud-widget-socials">
              <li>
                <a href="https://twitter.com/sumumacom" target="_blank" rel="noopener">
                  <i class="lni lni-twitter-filled"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-xl-2 col-lg-2 col-md-6 col-sm-6">
          <div class="ud-widget">
            <h5 class="ud-widget-title">利用案内</h5>
            <ul class="ud-widget-links">
              <li>
                <a href="{% url 'home:terms_of_service' %}" target=_blank rel=noopener>利用規約</a>
              </li>
              <li>
                <a href="{% url 'home:privacy_policy' %}" target=_blank rel=noopener>プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-xl-2 col-lg-3 col-md-6 col-sm-6">
          <div class="ud-widget">
            <h5 class="ud-widget-title">関連ページ</h5>
            <ul class="ud-widget-links">
              <li>
                <a href="{% url 'lp:general' %}" target=_blank rel=noopener>SUMUMA紹介ページ</a>
              </li>
              <li>
                <a href="https://alwaysblue.notion.site/d42d24d8f881422da25b420733924be5?v=d7d5d2f5831a45d9820c4e6d64a3962c" target=_blank rel=noopener>お知らせ</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-xl-2 col-lg-3 col-md-6 col-sm-6">
        </div>
        <div class="col-xl-3 col-lg-6 col-md-8 col-sm-10">
        </div>
      </div>
    </div>
  </div>
  <div class="ud-footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
        </div>
        <div class="col-md-4">
          <p class="ud-footer-bottom-right">
            &copy; 2018 SUMUMA
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

sumuma/templates/loggedin_base.html
<!doctype html>
<html lang="ja">
{% load tailwind_tags %}
<head>
  {% include 'gtm.html' %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% load static %}
  <!-- favicon -->
  <link rel="icon" type="image/png" href="{% static 'home/images/favicon.png' %}" alt="">
  <link rel="apple-touch-icon" href="{% static 'home/images/favicon.png' %}" alt="">
  <!-- jquery toast css -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'account/css/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css" rel="stylesheet" />
  {% tailwind_css %}
  <title>SUMUMA</title>
</head>
<body class="bg-green-50 font-sans leading-normal tracking-normal">
{% include 'gtm_noscript.html' %}
{% include 'loggedin_header.html' %}
<!-- jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- jquery toast js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js" integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- chart.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" integrity="sha512-a+mx2C3JS6qqBZMZhSI5LpWv8/4UK21XihyLKaFoSbiKQs/3yRdtqCwGuWZGwHKc5amlNN8Y7JlqnWQ6N/MYgA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<!-- alpine -->
<script
  src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js"
  defer
></script>
<script type="text/javascript" src="{% static 'sumuma/js/functions.js' %}"></script>
<div class="container w-full mx-auto pt-20">
  {% block content %}
  {% endblock %}
</div>
</body>
<html>

sumuma/templates/loggedin_header.html
<nav id="header" class="bg-white fixed w-full z-10 top-0 shadow">
  <div class="w-full container mx-auto flex flex-wrap items-center mt-0 pt-3 pb-3">
    <div class="w-1/2 pl-2 md:pl-0">
      <a class="pl-1 text-gray-900 text-base xl:text-xl no-underline hover:no-underline font-bold"
         href="{% url 'kakeibo:top' %}">SUMUMA</a>
    </div>
    <div class="w-1/2 pr-0">
      <div class="flex relative inline-block float-right">
        <div class="relative text-sm">
          <div id="userMenu"
               class="bg-white rounded shadow-md mt-2 absolute mt-12 top-0 right-0 min-w-full overflow-auto z-30 invisible">
            <ul class="list-reset">
              <li>
                <a href="#" class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">My
                  account</a>
              </li>
              <li>
                <a href="#" class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">Notifications</a>
              </li>
              <li>
                <hr class="border-t mx-2 border-gray-400">
              </li>
              <li>
                <a href="#" class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">Logout</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="block lg:hidden pr-4">
          <button id="nav-toggle"
                  class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-teal-500 appearance-none focus:outline-none">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <title>Menu</title>
              <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-white z-20"
         id="nav-content">
      <ul class="list-reset lg:flex flex-1 items-center px-4 md:px-0">
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'kakeibo:top' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'kakeibo' and request.resolver_match.url_name in 'top,records_top,records_latest_registration_list,edit_income,edit_expenditure,records_edit_income,records_edit_expenditure,records_edit_latest_income,records_edit_latest_expenditure' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fas fa-home fa-fw mr-3 {% if request.resolver_match.app_name == 'kakeibo' and request.resolver_match.url_name in 'top,records_top,records_latest_registration_list,edit_income,edit_expenditure,records_edit_income,records_edit_expenditure,records_edit_latest_income,records_edit_latest_expenditure' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">収支管理</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'kakeibo:categories' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.url_name == 'categories' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fas fa-home fa-fw mr-3 {% if request.resolver_match.url_name == 'categories' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">カテゴリー</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'shopping:top' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'shopping' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fas fa-home fa-fw mr-3 {% if request.resolver_match.app_name == 'shopping' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">買い物リスト</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'analyses:top' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'analyses' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fas fa-tasks fa-fw mr-3 {% if request.resolver_match.app_name == 'analyses' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">収支分析</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'budget:top' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'budget' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fa fa-envelope fa-fw mr-3 {% if request.resolver_match.app_name == 'budget' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">収支計画</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'account:user_detail' user.pk %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'account' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fas fa-chart-area fa-fw mr-3 {% if request.resolver_match.app_name == 'account' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">設定</span>
          </a>
        </li>
        <li class="mr-6 my-2 md:my-0">
          <a href="{% url 'contact:top' %}"
             class="block py-1 md:py-3 pl-1 align-middle no-underline border-b-2 {% if request.resolver_match.app_name == 'contact' %} text-pink-600 hover:text-pink-600 border-red-500 {% else %} border-white text-gray-500 hover:text-pink-600 hover:border-red-500 {% endif %}">
            <i
              class="fa fa-wallet fa-fw mr-3 {% if request.resolver_match.app_name == 'contact' %} text-pink-600 {% endif %}"></i>
            <span class="pb-1 md:pb-0 text-sm">お問い合わせ</span>
          </a>
        </li>
      </ul>
      <div class="relative pull-right pl-4 pr-4 md:pr-0">
        <a href="{% url 'account:logout' %}"
           class="bg-green-500 hover:bg-green-700 text-white hover:text-white font-bold py-2 px-4 rounded">ログアウト</a>
      </div>
    </div>
  </div>
</nav>

sumuma/templates/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    {% include 'gtm.html' %}
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>