kakeibo/urls.py
from django.urls import path

from .views import kakeibo, records

app_name = 'kakeibo'

urlpatterns = [
    path('', kakeibo.Top.as_view(), name='top'),
    path('create-income/', kakeibo.CreateIncome.as_view(), name='create_income'),
    path('create-expenditure/', kakeibo.CreateExpenditure.as_view(), name='create_expenditure'),
    path('edit-income/<int:pk>/', kakeibo.EditIncome.as_view(), name='edit_income'),
    path('edit-expenditure/<int:pk>/', kakeibo.EditExpenditure.as_view(), name='edit_expenditure'),
    path('delete-income/<int:pk>/', kakeibo.delete_income, name='delete_income'),
    path('delete-expenditure/<int:pk>/', kakeibo.delete_expenditure, name='delete_expenditure'),
    path('categories/', kakeibo.CategoryIndex.as_view(), name='categories'),
    path('create-category/', kakeibo.CreateCategory.as_view(), name='create_category'),
    path('delete-category/<int:pk>/', kakeibo.DeleteCategory.as_view(), name='delete_category'),
    # NOTE: records urls
    path('records/', records.Top.as_view(), name='records_top'),
    path('records/edit-income/<int:pk>/', records.EditIncome.as_view(), name='records_edit_income'),
    path('records/edit-expenditure/<int:pk>/', records.EditExpenditure.as_view(), name='records_edit_expenditure'),
    path("records/delete-income/<int:pk>/", records.delete_income, name='records_delete_income'),
    path("records/delete-expenditure/<int:pk>/", records.delete_expenditure, name='records_delete_expenditure'),
    path('records/latest-registration-list/', records.LatestRegistrationList.as_view(),
         name='records_latest_registration_list'),
    path('records/edit-latest-income/<int:pk>/', records.EditLatestIncome.as_view(), name='records_edit_latest_income'),
    path('records/edit-latest-expenditure/<int:pk>/', records.EditLatestExpenditure.as_view(),
         name='records_edit_latest_expenditure'),
    path("records/delete-latest-income/<int:pk>/", records.delete_latest_income, name='records_delete_latest_income'),
    path("records/delete-latest-expenditure/<int:pk>/", records.delete_latest_expenditure,
         name='records_delete_latest_expenditure'),
    path("records-export/", records.records_export, name='records_export'),
    path("records_import/", records.records_import, name='records_import'),
]

lp/urls.py
from django.urls import path

from . import views

app_name = 'lp'

urlpatterns = [
    path('general/', views.General.as_view(), name='general'),
]

sumuma/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
import environ
from rest_framework import permissions
from rest_framework import routers

from kakeibo.views.api.kakeibo import CategoriesViewSet, IncomesViewSet, ExpendituresViewSet
from sumuma.settings import ADMIN_DASHBOARD_PATH

env = environ.Env()

schema_view = get_schema_view(
    openapi.Info(
        title="SUMUMA API",
        default_version='v1',
        description="SUMUMA Swagger UI",
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticatedOrReadOnly],
)

router = routers.DefaultRouter()
router.register(r'categories', CategoriesViewSet, basename='categories')
router.register(r'incomes', IncomesViewSet, basename='incomes')
router.register(r'expenditures', ExpendituresViewSet, basename='expenditures')

urlpatterns = [
    path(ADMIN_DASHBOARD_PATH, admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('kakeibo/', include('kakeibo.urls')),
    path('analyses/', include('analyses.urls')),
    path('contact/', include('contact.urls')),
    path('budget/', include('budget.urls')),
    path('shopping/', include('shopping.urls')),
    path('lp/', include('lp.urls')),
    # NOTE: api routers
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # NOTE: swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('openapi/', get_schema_view(
    #     title="Your Project",
    #     description="API for all things …",
    #     version="1.0.0"
    # ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url': 'openapi-schema'}
    # ), name='swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

kakeibo/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class KakeiboLabel(models.TextChoices):
    EXPENDITURE = 'expenditure', '支出'
    INCOME = 'income', '収入'


class Categories(models.Model):
    label = models.CharField(_('label'), max_length=16, choices=KakeiboLabel.choices, default=KakeiboLabel.EXPENDITURE)
    name = models.CharField(_('name'), max_length=32)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Incomes(models.Model):
    amount = models.BigIntegerField(_('amount'), help_text=_('Please enter the amount.'))
    event_date = models.DateField(_('event date'), default=timezone.now, help_text=_('Please enter the event date.'))
    memo = models.TextField(_('memo'), max_length=1000, blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, help_text=_('Please enter the category.'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.amount)


class Expenditures(models.Model):
    amount = models.BigIntegerField(_('amount'), help_text=_('Please enter the amount.'))
    event_date = models.DateField(_('event date'), default=timezone.now, help_text=_('Please enter the event date.'))
    memo = models.TextField(_('memo'), max_length=1000, blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, help_text=_('Please enter the category.'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.amount)

kakeibo/views.py
import uuid
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from itertools import chain

from .forms import ExpenditureForm, IncomeForm, CategoryForm
from .models import Expenditure, Income, Categories
from sumuma.concerns.permission import OnlyYouExpenditureMixin, OnlyYouIncomeMixin

User = get_user_model()


class Top(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeibo/top.html'
    context_object_name = 'records'
    paginate_by = 10

    def get_queryset(self):
        today = datetime.today()
        one_month_ago_date = today - relativedelta(months=1, days=1)
        incomes_record = Income.objects.filter(user_id=self.request.user.id,
                                                event_date__range=[one_month_ago_date, today],
                                                deleted=False).select_related('category')
        expenditures_record = Expenditure.objects.filter(user_id=self.request.user.id,
                                                     event_date__range=[one_month_ago_date, today],
                                                     deleted=False).select_related('category')
        return sorted(chain(incomes_record, expenditures_record), key=lambda instance: instance.event_date, reverse=True)

    def get_context_data(self, **kwargs):
        one_month_ago_date = datetime.today() - relativedelta(months=1, days=1)
        context = super().get_context_data(**kwargs)
        event_date = []
        incomes = []
        expenditures = []
        # NOTE: 1ヶ月分の収支折れ線グラフデータを作成
        for day in range(32):
            date = one_month_ago_date + timedelta(day)
            income = \
                Income.objects.filter(user_id=self.request.user.id, event_date=date, deleted=False).aggregate(
                    sum_amount=Sum('amount'))['sum_amount']
            expenditure = \
                Expenditure.objects.filter(user_id=self.request.user.id, event_date=date, deleted=False).aggregate(
                    sum_amount=Sum('amount'))['sum_amount']
            if income:
                incomes.append(income)
            else:
                incomes.append(0)
            if expenditure:
                expenditures.append(expenditure)
            else:
                expenditures.append(0)
            event_date.append('{}/{}'.format(date.month, date.day))
        context['submit_token'] = set_submit_token(self.request)
        context['event_date'] = event_date
        context['incomes'] = incomes
        context['expenditures'] = expenditures
        context['expenditure_categories'] = Categories.objects.filter(
            label='expenditure',
            user=self.request.user
        ).values_list('id', flat=True)
        context['income_categories'] = Categories.objects.filter(
            label='income',
            user=self.request.user
        ).values_list('id', flat=True)
        return context

    def income_form(self):
        return IncomeForm(user=self.request.user)

    def expenditure_form(self):
        return ExpenditureForm(user=self.request.user)


class CreateIncome(LoginRequiredMixin, generic.CreateView):
    model = Income
    form_class = IncomeForm
    template_name = 'kakeibo/top.html'
    success_url = reverse_lazy('kakeibo:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, '収入を登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '登録に失敗しました。')
        return redirect(self.success_url)
        return redirect(self.success_url)


class CreateExpenditure(LoginRequiredMixin, generic.CreateView):
    model = Expenditure
    form_class = ExpenditureForm
    template_name = 'kakeibo/top.html'
    success_url = reverse_lazy('kakeibo:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, '支出を登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '登録に失敗しました。')
        return redirect(self.success_url)


class EditExpenditure(LoginRequiredMixin, OnlyYouExpenditureMixin, generic.UpdateView, generic.FormView):
    template_name = 'kakeibo/edit.html'
    model = Expenditure
    form_class = ExpenditureForm
    success_url = reverse_lazy('kakeibo:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        messages.success(self.request, "編集を更新しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした。")
        return redirect(self.success_url)


class EditIncome(LoginRequiredMixin, OnlyYouIncomeMixin, generic.UpdateView, generic.FormView):
    template_name = 'kakeibo/edit.html'
    model = Income
    form_class = IncomeForm
    success_url = reverse_lazy('kakeibo:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        messages.success(self.request, "編集を更新しました。")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "更新できませんでした。")


def delete_income(request, pk):
    if request.method == 'POST':
        income = Income.objects.get(pk=pk)
        income.deleted = True
        income.save()
        messages.success(request, '削除しました。')
        return redirect('kakeibo:top')


def delete_expenditure(request, pk):
    if request.method == 'POST':
        expenditure = Expenditure.objects.get(pk=pk)
        expenditure.deleted = True
        expenditure.save()
        messages.success(request, '削除しました。')
        return redirect('kakeibo:top')


def exists_submit_token(request):
    token_in_request = request.POST.get('submit_token')
    token_in_session = request.session.pop('submit_token', None)

    if not token_in_request:
        return False
    if not token_in_session:
        return False

    return token_in_request == token_in_session


def set_submit_token(request):
    submit_token = str(uuid.uuid4())
    request.session['submit_token'] = submit_token
    return submit_token


# NOTE: Category views


class CategoryIndex(LoginRequiredMixin, generic.ListView):
    template_name = 'kakeibo/categories.html'
    context_object_name = 'categories'
    model = Categories

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_token'] = set_submit_token(self.request)
        return context

    def category_form(self):
        return CategoryForm()


class CreateCategory(LoginRequiredMixin, generic.CreateView):
    model = Categories
    form_class = CategoryForm
    template_name = 'kakeibo/categories.html'
    success_url = reverse_lazy('kakeibo:categories')

    def form_valid(self, form):
        if not exists_submit_token(self.request):
            messages.error(self.request, '登録に失敗しました。')
            return redirect(self.success_url)

        existed_category = Categories.objects.filter(
            name=self.request.POST.get('name'),
            label=self.request.POST.get('label')
        ).first()

        if existed_category:
            messages.error(self.request, self.request.POST.get('name') + 'はすでに登録されています。')
            return redirect(self.success_url)

        form.instance.user = self.request.user
        messages.success(self.request, self.request.POST.get('name') + 'を登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '登録に失敗しました。')
        return redirect(self.success_url)


class DeleteCategory(LoginRequiredMixin, generic.DeleteView):
    model = Categories
    success_url = reverse_lazy('kakeibo:categories')

    def form_valid(self, form):
        Categories.objects.get(id=self.kwargs['pk']).delete()
        messages.success(self.request, '削除しました。')
        return redirect(self.success_url)

    def form_invalid(self, form):
        messages.success(self.request, '削除に失敗しました。')
        return redirect(self.success_url)

kakeibo/templates/records/delete_form.html
<div
  class="hidden overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none justify-center items-center"
  id="delete-modal">
  <div class="relative w-auto mx-2 my-6 mx-auto max-w-3xl">
    <form
      class="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none"
      id="delete-form"
      action=""
      method="post">
      {% csrf_token %}
      <input type='hidden' name='submit_token' value="{{ submit_token }}">
      <!--header-->
      <div class="flex items-start justify-between p-5 border-b border-solid border-blueGray-200 rounded-t">
        <h3 class="text-3xl font-semibold">
          本当に削除しますか？
        </h3>
        <button
          class="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
          onclick="toggleModal('delete-modal')">
          <span class="bg-transparent text-black opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
            ×
          </span>
        </button>
      </div>
      <!--footer-->
      <div class="flex items-center justify-end p-6 border-t border-solid border-blueGray-200 rounded-b">
        <button
          class="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
          type="button" onclick="toggleModal('delete-modal')">
          閉じる
        </button>
        <button class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" type="submit">
          削除
        </button>
      </div>
    </form>
  </div>
</div>

kakeibo/templates/records/top.html
{% extends "loggedin_base.html" %}
{% load static %}
{% load get_list %}
{% block content %}
  <div class="w-full md:px-0 md:mt-8 text-gray-800 leading-normal">
    <div class="p-3 pt-0">
      <div class="mt-2 p-3 bg-white shadow border-b border-gray-200 sm:rounded-lg pb-0">
        <div class="flex flex-wrap -mx-3 mb-6">
          <div class="w-full px-3">
            <div class="w-full flex pb-4 ">
              <form class="mr-3" action="{% url 'kakeibo:records_export' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="start_date" value="{{ request.GET.start_date }}">
                <input type="hidden" name="end_date" value="{{ request.GET.end_date }}">
                <input type="hidden" name="category_ids" value="{{ request.GET|get_list:'category_ids' }}">
                <button class="bg-gray-400 hover:bg-gray-500 text-white font-bold py-2 px-4 rounded">CSVエクスポート</button>
              </form>
              <form class="flex" action="{% url 'kakeibo:records_import' %}" method="post"
                    enctype="multipart/form-data">
                {% csrf_token %}
                <label for="kakeibo-csv"
                       class="block bg-gray-400 hover:bg-gray-500 text-white font-bold py-2 px-4 rounded-l cursor-pointer">
                  CSVインポート
                  <input id="kakeibo-csv" class="hidden" type="file" name="kakeibo-csv" accept="text/csv" required>
                </label>
                <button class="border border-gray-400 py-2 px-4 mr-2 rounded-r">ファイルを送信する</button>
              </form>
            </div>
            <form action="" method="get">
              {% csrf_token %}
              <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-1/2 px-3">
                  <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="select-role">
                    カテゴリー
                  </label>
                  <div class="relative mb-3">
                    <select
                      id="select-role"
                      name="category_ids"
                      autocomplete="off"
                      class="block w-full rounded-sm cursor-pointer focus:outline-none"
                      multiple
                    >
                      {% for category in categories %}
                        <option value="{{ category.pk }}">{{ category.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="w-1/2 px-3">
                  <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_category">
                    期間
                  </label>
                  <div class="w-full flex">
                    <div class="w-1/2">
                      <input type="date"
                             name="start_date"
                             class="w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white"
                             value={% if request.GET.start_date %} "{{ request.GET.start_date }}" {% else %} "{{ start_date }}" {% endif %}
                             required>
                    </div>
                    <div class="w-1/2 pl-3">
                      <input type="date"
                             name="end_date"
                             class="w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white"
                             value={% if request.GET.end_date %} "{{ request.GET.end_date }}" {% else %} "{{ end_date }}" {% endif %}
                             required>
                    </div>
                  </div>
                </div>
              </div>
              <button class="w-full bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"
                      type="submit">
                検索
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col px-3">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="pt-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">

                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  カテゴリー/日付
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  金額
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  メモ
                </th>
                <th scope="col" class="relative px-6 py-3">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
              {% for record in records %}
                <tr id="record{{ record.id }}">
                  <td class="px-6 py-4 whitespace-nowrap">
                    {% if record.category.label == 'expenditure' %}
                      <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-pink-100">
                        支出
                      </span>
                    {% elif record.category.label == 'income' %}
                      <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100">
                        収入
                      </span>
                    {% endif %}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="flex items-center">
                      <div class="ml-0">
                        <div class="text-sm font-medium text-gray-900">
                          {{ record.category }}
                        </div>
                        <div class="text-sm text-gray-500">
                          {{ record.event_date }}
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <div class="text-sm text-gray-900">
                      {{ record.amount }}
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <div class="text-sm text-gray-900">
                      {{ record.memo }}
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    {% if record.category.label == 'expenditure' %}
                      <a href="{% url 'kakeibo:records_edit_expenditure' pk=record.pk %}"
                         class="inline-block bg-green-500 hover:bg-green-700 text-white hover:text-white font-bold py-2 px-4 rounded">編集</a>
                      <button
                        class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded delete-button"
                        data-record-pk="{{ record.pk }}"
                        data-category="expenditure"
                        onclick="toggleModal('delete-modal')">
                        削除
                      </button>
                    {% elif record.category.label in 'income' %}
                      <a href="{% url 'kakeibo:records_edit_income' pk=record.pk %}"
                         class="inline-block bg-green-500 hover:bg-green-700 text-white hover:text-white font-bold py-2 px-4 rounded">編集</a>
                      <button
                        class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded delete-button"
                        data-record-pk="{{ record.pk }}"
                        data-category="income"
                        onclick="toggleModal('delete-modal')">
                        削除
                      </button>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include 'records/delete_form.html' %}
  <div class="hidden opacity-25 fixed inset-0 z-40 bg-black" id="delete-modal-backdrop"></div>
  {% include 'kakeibo/bottom_menu.html' %}
  <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
  <script type="text/javascript">
    new TomSelect('#select-role', {
      maxItems: 50,
      plugins: ['remove_button'],
      items: "{{ request.GET|get_list:'category_ids' }}".split(',')
    });
    {% for message in messages %}
      $.toast({
        icon: '{{ message.tags }}',
        text: '{{ message }}',
        position: 'bottom-right',
        showHideTransition: 'slide',
        hideAfter: 5000,
      });
    {% endfor %}
  </script>
  <script type="text/javascript" src="{% static 'records/js/functions.js' %}"></script>
{% endblock %}