lp/urls.py
from django.urls import path

from . import views

app_name = 'lp'

urlpatterns = [
    path('general/', views.General.as_view(), name='general'),
]

shopping/urls.py
from django.urls import path
from . import views

app_name = 'shopping'

urlpatterns = [
    path('todo/', views.Top.as_view(), name='top'),
    path('create-todo/', views.CreateToDo.as_view(), name='create_todo'),
    path('edit-todo/<int:pk>/', views.EditToDo.as_view(), name='edit_todo'),
    path('delete-todo/<int:pk>/', views.DeleteToDo.as_view(), name='delete_todo'),
]

sumuma/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
import environ
from rest_framework import permissions
from rest_framework import routers

from kakeibo.views.api.kakeibo import CategoriesViewSet, IncomesViewSet, ExpendituresViewSet
from sumuma.settings import ADMIN_DASHBOARD_PATH

env = environ.Env()

schema_view = get_schema_view(
    openapi.Info(
        title="SUMUMA API",
        default_version='v1',
        description="SUMUMA Swagger UI",
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticatedOrReadOnly],
)

router = routers.DefaultRouter()
router.register(r'categories', CategoriesViewSet, basename='categories')
router.register(r'incomes', IncomesViewSet, basename='incomes')
router.register(r'expenditures', ExpendituresViewSet, basename='expenditures')

urlpatterns = [
    path(ADMIN_DASHBOARD_PATH, admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('kakeibo/', include('kakeibo.urls')),
    path('analyses/', include('analyses.urls')),
    path('contact/', include('contact.urls')),
    path('budget/', include('budget.urls')),
    path('shopping/', include('shopping.urls')),
    path('lp/', include('lp.urls')),
    # NOTE: api routers
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # NOTE: swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('openapi/', get_schema_view(
    #     title="Your Project",
    #     description="API for all things …",
    #     version="1.0.0"
    # ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url': 'openapi-schema'}
    # ), name='swagger-ui'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

shopping/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from kakeibo.models import Expenditures, Categories

User = get_user_model()


class ToDo(models.Model):
    name = models.TextField(_('memo'), max_length=100, help_text=_('Please enter the name.'))
    amount = models.BigIntegerField(_('amount'), blank=True, null=True)
    event_date = models.DateField(
        _('event date'),
        blank=True,
        null=True,
        help_text=_('Please enter the event date.')
    )
    memo = models.TextField(_('memo'), max_length=1000, blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.DO_NOTHING, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_bought = models.BooleanField(_('is bought'), default=False)
    is_registered = models.BooleanField(_('is registered'), default=False)
    expenditure = models.ForeignKey(Expenditures, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.amount)

shopping/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from kakeibo.models import Categories
from .models import ToDo


class ToDoForm(forms.ModelForm):
    name = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 '
                     'mb-3 leading-tight focus:outline-none focus:bg-white'}),
    )
    amount = forms.IntegerField(
        required=False,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(9999999999999)
        ],
        widget=forms.NumberInput(attrs={
            'class': 'w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 '
                     'mb-3 leading-tight focus:outline-none focus:bg-white'}),
    )
    event_date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={
            'class': 'w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 '
                     'mb-3 leading-tight focus:outline-none focus:bg-white',
            'x-model': 'datepickerValue',
            '@click': 'showDatepicker = !showDatepicker',
            '@keydown.escape': 'showDatepicker = false',
            'readonly': 'readonly'
        }),
    )
    category = forms.ModelChoiceField(
        queryset=None,
        required=False,
        widget=forms.Select(attrs={
            'class': 'w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 '
                     'mb-3 leading-tight focus:outline-none focus:bg-white'}, ),
        empty_label='カテゴリーを選択してください'
    )
    memo = forms.CharField(
        max_length=1000,
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'w-full h-20 bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 '
                     'mb-3 leading-tight focus:outline-none focus:bg-white'}),
    )
    is_bought = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={
            'class': 'w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 mb-3'
        })
    )
    is_registered = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={
            'class': 'w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 mb-3'
        })
    )

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not user and kwargs['initial']['user']:
            user = kwargs['initial']['user']
        self.fields['category'].queryset = \
            Categories.objects.filter(label='expenditure', user=user)

    class Meta:
        model = ToDo
        fields = ['name', 'amount', 'event_date', 'category', 'memo', 'is_bought', 'is_registered']

shopping/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from kakeibo.models import Expenditures
from sumuma.concerns.permission import OnlyYouToDoMixin
from .forms import ToDoForm
from .models import ToDo

User = get_user_model()


class Top(LoginRequiredMixin, generic.ListView):
    template_name = 'shopping/todo.html'
    context_object_name = 'todos'
    paginate_by = 100
    model = ToDo

    def get_queryset(self):
        if self.request.GET.get('is_all') == 'on':
            return ToDo.objects.filter(user=self.request.user)
        return ToDo.objects.filter(is_bought=False, user=self.request.user)


class CreateToDo(LoginRequiredMixin, generic.CreateView):
    model = ToDo
    form_class = ToDoForm
    template_name = 'shopping/create_todo.html'
    success_url = reverse_lazy('shopping:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, '登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '登録に失敗しました。')
        return redirect(self.success_url)


class EditToDo(LoginRequiredMixin, OnlyYouToDoMixin, generic.UpdateView):
    model = ToDo
    form_class = ToDoForm
    template_name = 'shopping/edit_todo.html'
    success_url = reverse_lazy('shopping:top')

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user
        return initial

    @transaction.atomic
    def form_valid(self, form):
        user = self.request.user
        instance = form.instance
        form.instance.user = user
        if instance.is_registered and not form.instance.expenditure:
            expenditure = Expenditures.objects.create(user=user, category=instance.category,
                                                      event_date=instance.event_date,
                                                      amount=instance.amount, memo=instance.memo)
            form.instance.expenditure = expenditure
        form.save()
        messages.success(self.request, '更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '更新に失敗しました。')
        return redirect(self.success_url)


class DeleteToDo(LoginRequiredMixin, OnlyYouToDoMixin, generic.DeleteView):
    model = ToDo
    success_url = reverse_lazy('shopping:top')

    def form_valid(self, form):
        ToDo.objects.get(id=self.kwargs['pk']).delete()
        messages.success(self.request, '削除しました。')
        return redirect(self.success_url)

    def form_invalid(self, form):
        messages.success(self.request, '削除に失敗しました。')
        return redirect(self.success_url)

shopping/templates/shopping/create.html
{% extends "loggedin_base.html" %}
<style>
    [x-cloak] {
        display: none;
    }
</style>
{% block content %}
  <div class="w-full md:px-0 md:mt-8 text-gray-800 leading-normal">
    <!--content-->
    <form class="pt-0 pb-8" action="" method="post">
      {% csrf_token %}
      <input type='hidden' name='submit_token' value="{{ submit_token }}">
      <!--body-->
      <div class="pb-4">
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_name">
            名前
          </label>
          {{ form.name }}
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_amount">
            金額
          </label>
          {{ form.amount }}
        </div>
        <div class="w-full px-3">
          <div x-data="app()" x-init="[initDate(), getNoOfDays()]" x-cloak>
            <label for="datepicker" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
              日付
            </label>
            <div class="relative">
              <!--                    <input type="hidden" name="event_date" x-ref="date" />-->
              {{ form.event_date }}
              <div class="absolute top-0 right-0 px-3 py-2">
                <svg
                  class="h-6 w-6 text-gray-400"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                  />
                </svg>
              </div>
              <div
                class="bg-white mt-12 rounded-lg shadow p-4 absolute top-0 left-0 z-10"
                style="width: 17rem"
                x-show.transition="showDatepicker"
                @click.away="showDatepicker = false"
              >
                <div class="flex justify-between items-center mb-2">
                  <div>
                    <span
                      x-text="MONTH_NAMES[month]"
                      class="text-lg font-bold text-gray-800"
                    ></span>
                    <span
                      x-text="year"
                      class="ml-1 text-lg text-gray-600 font-normal"
                    ></span>
                  </div>
                  <div>
                    <button
                      type="button"
                      class="transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full"
                      :class="{'cursor-not-allowed opacity-25': month == 0 }"
                      :disabled="month == 0 ? true : false"
                      @click="month--; getNoOfDays()"
                    >
                      <svg
                        class="h-6 w-6 text-gray-500 inline-flex"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M15 19l-7-7 7-7"
                        />
                      </svg>
                    </button>
                    <button
                      type="button"
                      class="transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full"
                      :class="{'cursor-not-allowed opacity-25': month == 11 }"
                      :disabled="month == 11 ? true : false"
                      @click="month++; getNoOfDays()"
                    >
                      <svg
                        class="h-6 w-6 text-gray-500 inline-flex"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M9 5l7 7-7 7"
                        />
                      </svg>
                    </button>
                  </div>
                </div>

                <div class="flex flex-wrap mb-3 -mx-1">
                  <template x-for="(day, index) in DAYS" :key="index">
                    <div style="width: 14.26%" class="px-1">
                      <div
                        x-text="day"
                        class="text-gray-800 font-medium text-center text-xs"
                      ></div>
                    </div>
                  </template>
                </div>

                <div class="flex flex-wrap -mx-1">
                  <template x-for="blankday in blankDays">
                    <div
                      style="width: 14.28%"
                      class="text-center border p-1 border-transparent text-sm"
                    ></div>
                  </template>
                  <template
                    x-for="(date, dateIndex) in no_of_days"
                    :key="dateIndex"
                  >
                    <div style="width: 14.28%" class="px-1 mb-1">
                      <div
                        @click="getDateValue(date)"
                        x-text="date"
                        class="cursor-pointer text-center text-sm leading-none rounded-full leading-loose transition ease-in-out duration-100"
                        :class="{'bg-blue-500 text-white': isToday(date) == true, 'text-gray-700 hover:bg-blue-200': isToday(date) == false }"
                      ></div>
                    </div>
                  </template>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_category">
            カテゴリー
          </label>
          {{ form.category }}
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_memo">
            メモ
          </label>
          {{ form.memo }}
        </div>
      </div>
      <div class="px-3">
        <button class="w-full bg-green-500 hover:bg-green-700 text-white hover:text-white font-bold py-2 px-4 rounded"
                type="submit">更新
        </button>
      </div>
    </form>
  </div>
  {% load static %}
  <script type="text/javascript" src="{% static 'kakeibo_management/js/functions.js' %}"></script>
  <script type="text/javascript">
    {% for message in messages %}
      $.toast({
        icon: '{{ message.tags }}',
        text: '{{ message }}',
        position: 'bottom-right',
        showHideTransition: 'slide',
        hideAfter: 5000,
      });
    {% endfor %}

    // Datepicker
    const MONTH_NAMES = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "９月", "10月", "11月", "12月",];
    const DAYS = ["日", "月", "火", "水", "木", "金", "土"];

    function app() {
      return {
        showDatepicker: false, datepickerValue: "",

        month: "", year: "", no_of_days: [], blankDays: [], days: DAYS,

        initDate() {
          let today = new Date();
          this.month = today.getMonth();
          this.year = today.getFullYear();
          let thisDay = new Date(this.year, this.month, today.getDate());
          this.datepickerValue = thisDay.getFullYear() + '-' + ('00' + (thisDay.getMonth() + 1)).slice(-2) + '-' + ('00' + thisDay.getDate()).slice(-2);
        },

        isToday(date) {
          const today = new Date();
          const d = new Date(this.year, this.month, date);

          return today.toDateString() === d.toDateString() ? true : false;
        },

        getDateValue(date) {
          let selectedDate = new Date(this.year, this.month, date);
          this.datepickerValue = selectedDate.getFullYear() + '-' + ('00' + (selectedDate.getMonth() + 1)).slice(-2) + '-' + ('00' + selectedDate.getDate()).slice(-2);
          this.showDatepicker = false;
        },

        getNoOfDays() {
          let daysInMonth = new Date(this.year, parseInt(this.month) + 1, 0).getDate();

          // find where to start calendar day of week
          let dayOfWeek = new Date(this.year, this.month).getDay();
          let blankDaysArray = [];
          for (let i = 1; i <= dayOfWeek; i++) {
            blankDaysArray.push(i);
          }

          let daysArray = [];
          for (let i = 1; i <= daysInMonth; i++) {
            daysArray.push(i);
          }

          this.blankDays = blankDaysArray;
          this.no_of_days = daysArray;
        },
      };
    }
  </script>
  <script type="text/javascript" src="{% static 'kakeibo_management/js/functions.js' %}"></script>
{% endblock %}

shopping/templates/shopping/edit_todo.html
{% extends "loggedin_base.html" %}
<style>
    [x-cloak] {
        display: none;
    }
</style>
{% block content %}
  <div class="w-full md:px-0 md:mt-8 text-gray-800 leading-normal">
    <!--content-->
    <form class="pt-0 pb-8" action="" method="post">
      {% csrf_token %}
      <input type='hidden' name='submit_token' value="{{ submit_token }}">
      <!--body-->
      <div class="pb-4">
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_name">
            名前
          </label>
          {{ form.name }}
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_amount">
            金額
          </label>
          {{ form.amount }}
        </div>
        <div class="w-full px-3">
          <div x-data="app()" x-init="[initDate(), getNoOfDays()]" x-cloak>
            <label for="datepicker" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">
              購入予定日
            </label>
            <div class="relative">
              <!--                    <input type="hidden" name="event_date" x-ref="date" />-->
              {{ form.event_date }}
              <div class="absolute top-0 right-0 px-3 py-2">
                <svg
                  class="h-6 w-6 text-gray-400"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                  />
                </svg>
              </div>
              <div
                class="bg-white mt-12 rounded-lg shadow p-4 absolute top-0 left-0 z-10"
                style="width: 17rem"
                x-show.transition="showDatepicker"
                @click.away="showDatepicker = false"
              >
                <div class="flex justify-between items-center mb-2">
                  <div>
                    <span
                      x-text="MONTH_NAMES[month]"
                      class="text-lg font-bold text-gray-800"
                    ></span>
                    <span
                      x-text="year"
                      class="ml-1 text-lg text-gray-600 font-normal"
                    ></span>
                  </div>
                  <div>
                    <button
                      type="button"
                      class="transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full"
                      :class="{'cursor-not-allowed opacity-25': month == 0 }"
                      :disabled="month == 0 ? true : false"
                      @click="month--; getNoOfDays()"
                    >
                      <svg
                        class="h-6 w-6 text-gray-500 inline-flex"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M15 19l-7-7 7-7"
                        />
                      </svg>
                    </button>
                    <button
                      type="button"
                      class="transition ease-in-out duration-100 inline-flex cursor-pointer hover:bg-gray-200 p-1 rounded-full"
                      :class="{'cursor-not-allowed opacity-25': month == 11 }"
                      :disabled="month == 11 ? true : false"
                      @click="month++; getNoOfDays()"
                    >
                      <svg
                        class="h-6 w-6 text-gray-500 inline-flex"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M9 5l7 7-7 7"
                        />
                      </svg>
                    </button>
                  </div>
                </div>

                <div class="flex flex-wrap mb-3 -mx-1">
                  <template x-for="(day, index) in DAYS" :key="index">
                    <div style="width: 14.26%" class="px-1">
                      <div
                        x-text="day"
                        class="text-gray-800 font-medium text-center text-xs"
                      ></div>
                    </div>
                  </template>
                </div>

                <div class="flex flex-wrap -mx-1">
                  <template x-for="blankday in blankDays">
                    <div
                      style="width: 14.28%"
                      class="text-center border p-1 border-transparent text-sm"
                    ></div>
                  </template>
                  <template
                    x-for="(date, dateIndex) in no_of_days"
                    :key="dateIndex"
                  >
                    <div style="width: 14.28%" class="px-1 mb-1">
                      <div
                        @click="getDateValue(date)"
                        x-text="date"
                        class="cursor-pointer text-center text-sm leading-none rounded-full leading-loose transition ease-in-out duration-100"
                        :class="{'bg-blue-500 text-white': isToday(date) == true, 'text-gray-700 hover:bg-blue-200': isToday(date) == false }"
                      ></div>
                    </div>
                  </template>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_category">
            カテゴリー
          </label>
          {{ form.category }}
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_category">
            メモ
          </label>
          {{ form.memo }}
        </div>
        <div class="w-full px-3">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_is_bought">
            完了チェック
          </label>
          {{ form.is_bought }}
        </div>
        <div class="w-full px-3">
          {% if form.is_registered.value %}
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_is_registered">
              支出に登録済み
            </label>
            <input type="checkbox"
                   class="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 mb-3" id="id_is_registered" checked
                   disabled>
            <div class="hidden">
              {{ form.is_registered }}
            </div>
          {% else %}
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_is_registered">
              更新時に支出へ同時登録する
            </label>
            {{ form.is_registered }}
          {% endif %}
        </div>
      </div>
      <div class="px-3">
        <button class="w-full bg-green-500 hover:bg-green-700 text-white hover:text-white font-bold py-2 px-4 rounded"
                type="submit">更新
        </button>
      </div>
    </form>
  </div>
  {% load static %}
  <script type="text/javascript">
    {% for message in messages %}
      $.toast({
        icon: '{{ message.tags }}',
        text: '{{ message }}',
        position: 'bottom-right',
        showHideTransition: 'slide',
        hideAfter: 5000,
      });
    {% endfor %}

    // Datepicker
    const MONTH_NAMES = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "９月", "10月", "11月", "12月",];
    const DAYS = ["日", "月", "火", "水", "木", "金", "土"];

    function app() {
      return {
        showDatepicker: false, datepickerValue: "",

        month: "", year: "", no_of_days: [], blankDays: [], days: DAYS,

        initDate() {
          const idEventDate = document.getElementById('id_event_date');
          const date = new Date(idEventDate.value);
          this.month = date.getMonth();
          this.year = date.getFullYear();
          let thisDay = new Date(this.year, this.month, date.getDate());
          this.datepickerValue = thisDay.getFullYear() + '-' + ('00' + (thisDay.getMonth() + 1)).slice(-2) + '-' + ('00' + thisDay.getDate()).slice(-2);
        },

        isToday(date) {
          const today = new Date();
          const d = new Date(this.year, this.month, date);

          return today.toDateString() === d.toDateString() ? true : false;
        },

        getDateValue(date) {
          let selectedDate = new Date(this.year, this.month, date);
          this.datepickerValue = selectedDate.getFullYear() + '-' + ('00' + (selectedDate.getMonth() + 1)).slice(-2) + '-' + ('00' + selectedDate.getDate()).slice(-2);
          this.showDatepicker = false;
        },

        getNoOfDays() {
          let daysInMonth = new Date(this.year, parseInt(this.month) + 1, 0).getDate();

          // find where to start calendar day of week
          let dayOfWeek = new Date(this.year, this.month).getDay();
          let blankDaysArray = [];
          for (let i = 1; i <= dayOfWeek; i++) {
            blankDaysArray.push(i);
          }

          let daysArray = [];
          for (let i = 1; i <= daysInMonth; i++) {
            daysArray.push(i);
          }

          this.blankDays = blankDaysArray;
          this.no_of_days = daysArray;
        },
      };
    }
  </script>
{% endblock %}